SOURCEFILES = DesktopApp/Tester.java DesktopApp/AcceptTerms.java \
	      DesktopApp/SignIn.java DesktopApp/Register.java \
	      DesktopApp/GuiAux.java

EXEFILES = DesktopApp.Tester

test:
	javac $(SOURCEFILES)
	java $(EXEFILES)
